### ISSUE TITLE
Need a LICENSE file

### ISSUE THREAD

**Issue by tdunning** [digitalgreenorg/farmstack-open#12]
This repository needs a LICENSE file to clarify conditions for re-use.

My own suggestion is always an MIT or Apache 2 license, but the use of IDSA components may require a GPL license. In any case, you should let your downstream users know what's what. Having this in a LICENSE file also helps github and other automated tools understand and check your constraints.

Note that some licenses of your dependencies may also require a NOTICE file.

**Comment by mgautam099** [comment]
License information added to project

**Comment by tdunning** [comment]
And Github recognized the license correctly!  Yay.

Nice.
